# Generated by Django 2.2.19 on 2021-04-04 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('PK_Company', models.AutoField(db_column='PK_Company', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('PK_Excursion', models.AutoField(db_column='PK_Excursion', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_of_puzzle', max_length=200)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('price', models.IntegerField(db_column='price')),
                ('imagepath', models.ImageField(blank=True, db_column='imagePath', null=True, upload_to='photos')),
            ],
            options={
                'db_table': 'Excursion',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('PK_Place', models.AutoField(db_column='PK_Place', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('imagepath', models.ImageField(blank=True, db_column='imagePath', null=True, upload_to='photos')),
            ],
            options={
                'db_table': 'Place',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('PK_Schedule', models.AutoField(db_column='PK_Schedule', primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(blank=True, db_column='datetime', null=True)),
                ('PK_Excursion', models.ForeignKey(db_column='PK_Excursion', on_delete=django.db.models.deletion.DO_NOTHING, to='excursion_app.Excursion')),
            ],
            options={
                'db_table': 'Schedule',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('PK_Guide', models.AutoField(db_column='PK_Guide', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('phone', models.CharField(db_column='phone', max_length=11)),
                ('PK_Company', models.ForeignKey(db_column='PK_Company', on_delete=django.db.models.deletion.DO_NOTHING, to='excursion_app.Company')),
            ],
            options={
                'db_table': 'Guide',
            },
        ),
        migrations.AddField(
            model_name='excursion',
            name='PK_Guide',
            field=models.ForeignKey(db_column='PK_Guide', on_delete=django.db.models.deletion.DO_NOTHING, to='excursion_app.Guide'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='PK_Place',
            field=models.ForeignKey(db_column='PK_Place', on_delete=django.db.models.deletion.DO_NOTHING, to='excursion_app.Place'),
        ),
    ]
